language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "node"
install:
  - cd website && npm install
script:
  - npm run build
branches:
  except:
    - master
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/isomorphic-git.github.io
  target_branch: master
  on:
    branch: source