language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "node"
branches:
  only:
    - source
install:
  - cd website && npm install
script:
  - npm run build
after_script:
  - git config --global user.email "deploy@travis-ci.org"
  - git config --global user.name "Deployment Bot"
  - echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
  - npm run publish-gh-pages
